spring.application.name=ems-java-backend

# Config Backend Port
server.port=8080

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:8889/ems
spring.datasource.username=root
spring.datasource.password=root

# Hibernate Settings
spring.jpa.hibernate.ddl-auto=update

